name = "AI-Forever"
uid = "9c03d4a8-3af4-48d7-0001-012e1f313dc1"
version = 1
copyright = "Azraeel"
description = "(FAF) AI-Forever"
author = "Azraeel"
url = ""
icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
